server:
  port: 6064

outer-service:
  translator: http://translator:6032
  avatar: http://avatar:6016
signature:
  secret: victor
credentials:
  pass: foo-bar-bazz

spring:
  datasource:
    url: jdbc:postgresql://database:5432/dating
    username: postgres
    password: postgres
    hikari:
      schema: dating
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    url: jdbc:postgresql://database:5432/dating
    schemas:
      - dating
    user: postgres
    password: postgres
  jackson:
    serialization:
      fail-on-empty-beans: false




