server:
  port: 6064

outer-service:
  translator: http://localhost:6032
  avatar: http://localhost:6016
signature:
  secret: victor

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dating
    username: postgres
    password: postgres
    hikari:
      schema: dating
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    url: jdbc:postgresql://localhost:5432/dating
    schemas:
      - dating
    user: postgres
    password: postgres
  jackson:
    serialization:
      fail-on-empty-beans: false
logging:
  level:
    sql: TRACE
    org.springframework.jdbc.core: TRACE




